source 'https://rubygems.org'

gem 'pry'
gem 'rspec'
gem 'activerecord', '~> 6.1.7', :require => 'active_record'
gem 'sinatra-activerecord'
gem 'sqlite3', '~> 1.3.6'
gem 'rake'
gem 'database_cleaner'
gem 'require_all'
